import torch
import random
from diffusers import StableDiffusion3Pipeline


pipe = StableDiffusion3Pipeline.from_pretrained("stabilityai/stable-diffusion-3-medium-diffusers", torch_dtype=torch.float32) # torch_dtype=torch.float16)
pipe = pipe.to("cuda")

#pipe = StableDiffusion3Pipeline.from_pretrained("stabilityai/stable-diffusion-3-medium-diffusers", torch_dtype=torch.float16)
pipe.enable_model_cpu_offload()
#pipe = pipe.to("cuda")


'''
prompts = [
    "High-resolution DSLR photo of a single whole with white background, unsliced apple with smooth. The apple is flying in space 1000 meters, with no plain underneath is shown. neutral background with soft, making the apple in sharp focus and the background slightly blurred.",
    "High-resolution DSLR photo of a single whole with white background, unsliced apricot with smooth, orange skin. The apricot is flying in space 1000 meters, with no plain underneath is shown. neutral background with soft, natural lighting and a shallow depth of field, making the apricot in sharp focus and the background slightly blurred.",
    "High-resolution DSLR photo of a single whole with white background, unsliced avocado with smooth green skin. The avocado is flying in space 1000 meters, with no plain underneath is shown. neutral background with soft, natural lighting and a shallow depth of field, making the avocado in sharp focus and the background slightly blurred.",
    "High-resolution DSLR photo of a single whole with white background, unsliced banana with vibrant yellow skin. The banana is flying in space 1000 meters, with no plain underneath is shown. neutral background with soft, natural lighting and a shallow depth of field, making the banana in sharp focus and the background slightly blurred.",
    "High-resolution DSLR photo of a single whole with white background, unsliced blackberry with deep purple-black color and textured surface. The blackberry is flying in space 1000 meters, with no plain underneath is shown. neutral background with soft, natural lighting and a shallow depth of field, making the blackberry in sharp focus and the background slightly blurred.",
    "High-resolution DSLR photo of a single whole with white background, unsliced blueberry with smooth, blue skin. The blueberry is flying in space 1000 meters, with no plain underneath is shown. neutral background with soft, natural lighting and a shallow depth of field, making the blueberry in sharp focus and the background slightly blurred.",
    "High-resolution DSLR photo of a single whole with white background, unsliced cantaloupe with rough, netted skin. The cantaloupe is flying in space 1000 meters, with no plain underneath is shown. neutral background with soft, natural lighting and a shallow depth of field, making the cantaloupe in sharp focus and the background slightly blurred.",
    "High-resolution DSLR photo of a single whole with white background, unsliced cherry with smooth, red skin. The cherry is flying in space 1000 meters, with no plain underneath is shown. neutral background with soft, natural lighting and a shallow depth of field, making the cherry in sharp focus and the background slightly blurred.",
    "High-resolution DSLR photo of a single whole with white background, unsliced coconut with rough, brown husk. The coconut is flying in space 1000 meters, with no plain underneath is shown. neutral background with soft, natural lighting and a shallow depth of field, making the coconut in sharp focus and the background slightly blurred.",
    "High-resolution DSLR photo of a single whole with white background, unsliced cranberry with smooth, red skin. The cranberry is flying in space 1000 meters, with no plain underneath is shown. neutral background with soft, natural lighting and a shallow depth of field, making the cranberry in sharp focus and the background slightly blurred.",
    "High-resolution DSLR photo of a single whole with white background, unsliced date with smooth, brown skin. The date is flying in space 1000 meters, with no plain underneath is shown. neutral background with soft, natural lighting and a shallow depth of field, making the date in sharp focus and the background slightly blurred.",
    "High-resolution DSLR photo of a single whole with white background, unsliced dragonfruit with vibrant pink skin and green scales. The dragonfruit is flying in space 1000 meters, with no plain underneath is shown. neutral background with soft, natural lighting and a shallow depth of field, making the dragonfruit in sharp focus and the background slightly blurred.",
    "High-resolution DSLR photo of a single whole with white background, unsliced durian with spiky, greenish-brown skin. The durian is flying in space 1000 meters, with no plain underneath is shown. neutral background with soft, natural lighting and a shallow depth of field, making the durian in sharp focus and the background slightly blurred.",
    "High-resolution DSLR photo of a single whole with white background, unsliced fig with smooth, purple skin. The fig is flying in space 1000 meters, with no plain underneath is shown. neutral background with soft, natural lighting and a shallow depth of field, making the fig in sharp focus and the background slightly blurred.",
    "High-resolution DSLR photo of a single whole with white background, unsliced grape with smooth, green skin. The grape is flying in space 1000 meters, with no plain underneath is shown. neutral background with soft, natural lighting and a shallow depth of field, making the grape in sharp focus and the background slightly blurred.",
    "High-resolution DSLR photo of a single whole with white background, unsliced guava with smooth, green skin. The guava is flying in space 1000 meters, with no plain underneath is shown. neutral background with soft, natural lighting and a shallow depth of field, making the guava in sharp focus and the background slightly blurred.",
    "High-resolution DSLR photo of a single whole with white background, unsliced honeydew melon with smooth, pale yellow skin. The honeydew is flying in space 1000 meters, with no plain underneath is shown. neutral background with soft, natural lighting and a shallow depth of field, making the honeydew in sharp focus and the background slightly blurred.",
    "High-resolution DSLR photo of a single whole with white background, unsliced kiwi with fuzzy, brown skin. The kiwi is flying in space 1000 meters, with no plain underneath is shown. neutral background with soft, natural lighting and a shallow depth of field, making the kiwi in sharp focus and the background slightly blurred.",
    "High-resolution DSLR photo of a single whole with white background, unsliced lemon with smooth, yellow skin. The lemon is flying in space 1000 meters, with no plain underneath is shown. neutral background with soft, natural lighting and a shallow depth of field, making the lemon in sharp focus and the background slightly blurred.",
    "High-resolution DSLR photo of a single whole with white background, unsliced lime with smooth, green skin. The lime is flying in space 1000 meters, with no plain underneath is shown. neutral background with soft, natural lighting and a shallow depth of field, making the lime in sharp focus and the background slightly blurred.",
    "High-resolution DSLR photo of a single whole with white background, unsliced lychee with rough, pink-red skin. The lychee is flying in space 1000 meters, with no plain underneath is shown. neutral background with soft, natural lighting and a shallow depth of field, making the lychee in sharp focus and the background slightly blurred.",
    "High-resolution DSLR photo of a single whole with white background, unsliced mango with smooth, red-yellow skin. The mango is flying in space 1000 meters, with no plain underneath is shown. neutral background with soft, natural lighting and a shallow depth of field, making the mango in sharp focus and the background slightly blurred.",
    "High-resolution DSLR photo of a single whole with white background, unsliced nectarine with smooth, red-yellow skin. The nectarine is flying in space 1000 meters, with no plain underneath is shown. neutral background with soft, natural lighting and a shallow depth of field, making the nectarine in sharp focus and the background slightly blurred.",
    "High-resolution DSLR photo of a single whole with white background, unsliced orange with smooth, orange skin. The orange is flying in space 1000 meters, with no plain underneath is shown. neutral background with soft, natural lighting and a shallow depth of field, making the orange in sharp focus and the background slightly blurred.",
    "High-resolution DSLR photo of a single whole with white background, unsliced papaya with smooth, yellow-green skin. The papaya is flying in space 1000 meters, with no plain underneath is shown. neutral background with soft, natural lighting and a shallow depth of field, making the papaya in sharp focus and the background slightly blurred."
    "High-resolution DSLR photo of a single whole with white background, unsliced passionfruit with smooth, purple skin. The passionfruit is flying in space 1000 meters, with no plain underneath is shown. neutral background with soft, natural lighting and a shallow depth of field, making the passionfruit in sharp focus and the background slightly blurred.",
    "High-resolution DSLR photo of a single whole with white background, unsliced pear with smooth, green-yellow skin. The pear is flying in space 1000 meters, with no plain underneath is shown. neutral background with soft, natural lighting and a shallow depth of field, making the pear in sharp focus and the background slightly blurred.",
    "High-resolution DSLR photo of a single whole with white background, unsliced persimmon with smooth, orange skin. The persimmon is flying in space 1000 meters, with no plain underneath is shown. neutral background with soft, natural lighting and a shallow depth of field, making the persimmon in sharp focus and the background slightly blurred.",
    "High-resolution DSLR photo of a single whole with white background, unsliced pineapple with rough, spiky, green-brown skin. The pineapple is flying in space 1000 meters, with no plain underneath is shown. neutral background with soft, natural lighting and a shallow depth of field, making the pineapple in sharp focus and the background slightly blurred.",
    "High-resolution DSLR photo of a single whole with white background, unsliced plum with smooth, purple-red skin. The plum is flying in space 1000 meters, with no plain underneath is shown. neutral background with soft, natural lighting and a shallow depth of field, making the plum in sharp focus and the background slightly blurred.",
    "High-resolution DSLR photo of a single whole with white background, unsliced pomegranate with smooth, red skin. The pomegranate is flying in space 1000 meters, with no plain underneath is shown. neutral background with soft, natural lighting and a shallow depth of field, making the pomegranate in sharp focus and the background slightly blurred.",
    "High-resolution DSLR photo of a single whole with white background, unsliced raspberry with vibrant red color and textured surface. The raspberry is flying in space 1000 meters, with no plain underneath is shown. neutral background with soft, natural lighting and a shallow depth of field, making the raspberry in sharp focus and the background slightly blurred.",
    "High-resolution DSLR photo of a single whole with white background, unsliced strawberry with vibrant red skin and green leaves. The strawberry is flying in space 1000 meters, with no plain underneath is shown. neutral background with soft, natural lighting and a shallow depth of field, making the strawberry in sharp focus and the background slightly blurred.",
    "High-resolution DSLR photo of a single whole with white background, unsliced ugli fruit with rough, yellow-green skin. The ugli fruit is flying in space 1000 meters, with no plain underneath is shown. neutral background with soft, natural lighting and a shallow depth of field, making the ugli fruit in sharp focus and the background slightly blurred.",
    "High-resolution DSLR photo of a single whole with white background, unsliced watermelon with smooth, green-striped skin. The watermelon is flying in space 1000 meters, with no plain underneath is shown. neutral background with soft, natural lighting and a shallow depth of field, making the watermelon in sharp focus and the background slightly blurred.",
    "High-resolution DSLR photo of a single whole with white background, unsliced carrot with smooth, orange skin. The carrot is flying in space 1000 meters, with no plain underneath is shown. neutral background with soft, natural lighting and a shallow depth of field, making the carrot in sharp focus and the background slightly blurred.",
    "High-resolution DSLR photo of a single whole with white background, unsliced broccoli with dark green florets. The broccoli is flying in space 1000 meters, with no plain underneath is shown. neutral background with soft, natural lighting and a shallow depth of field, making the broccoli in sharp focus and the background slightly blurred.",
    "High-resolution DSLR photo of a single whole with white background, unsliced cauliflower with white, bumpy florets. The cauliflower is flying in space 1000 meters, with no plain underneath is shown. neutral background with soft, natural lighting and a shallow depth of field, making the cauliflower in sharp focus and the background slightly blurred.",
    "High-resolution DSLR photo of a single whole with white background, unsliced bell pepper with smooth, vibrant red skin. The bell pepper is flying in space 1000 meters, with no plain underneath is shown. neutral background with soft, natural lighting and a shallow depth of field, making the bell pepper in sharp focus and the background slightly blurred.",
    "High-resolution DSLR photo of a single whole with white background, unsliced pumpkin with rough, orange skin. The pumpkin is flying in space 1000 meters, with no plain underneath is shown. neutral background with soft, natural lighting and a shallow depth of field, making the pumpkin in sharp focus and the background slightly blurred.",
    "High-resolution DSLR photo of a single whole with white background, unsliced cucumber with smooth, green skin. The cucumber is flying in space 1000 meters, with no plain underneath is shown. neutral background with soft, natural lighting and a shallow depth of field, making the cucumber in sharp focus and the background slightly blurred.",
    "High-resolution DSLR photo of a single whole with white background, unsliced tomato with smooth, red skin. The tomato is flying in space 1000 meters, with no plain underneath is shown. neutral background with soft, natural lighting and a shallow depth of field, making the tomato in sharp focus and the background slightly blurred.",
    "High-resolution DSLR photo of a single whole with white background, unsliced eggplant with smooth, deep purple skin. The eggplant is flying in space 1000 meters, with no plain underneath is shown. neutral background with soft, natural lighting and a shallow depth of field, making the eggplant in sharp focus and the background slightly blurred.",
    "High-resolution DSLR photo of a single whole with white background, unsliced zucchini with smooth, green skin. The zucchini is flying in space 1000 meters, with no plain underneath is shown. neutral background with soft, natural lighting and a shallow depth of field, making the zucchini in sharp focus and the background slightly blurred.",
    "High-resolution DSLR photo of a single whole with white background, unsliced potato with rough, brown skin. The potato is flying in space 1000 meters, with no plain underneath is shown. neutral background with soft, natural lighting and a shallow depth of field, making the potato in sharp focus and the background slightly blurred.",
    "High-resolution DSLR photo of a single whole with white background, unsliced onion with smooth, golden brown skin. The onion is flying in space 1000 meters, with no plain underneath is shown. neutral background with soft, natural lighting and a shallow depth of field, making the onion in sharp focus and the background slightly blurred.",
    "High-resolution DSLR photo of a single whole with white background, unsliced garlic with papery white skin. The garlic is flying in space 1000 meters, with no plain underneath is shown. neutral background with soft, natural lighting and a shallow depth of field, making the garlic in sharp focus and the background slightly blurred.",
    "High-resolution DSLR photo of a single whole with white background, unsliced lettuce with vibrant green leaves. The lettuce is flying in space 1000 meters, with no plain underneath is shown. neutral background with soft, natural lighting and a shallow depth of field, making the lettuce in sharp focus and the background slightly blurred.",
    "High-resolution DSLR photo of a single whole with white background, unsliced corn on the cob with golden yellow kernels. The corn is flying in space 1000 meters, with no plain underneath is shown. neutral background with soft, natural lighting and a shallow depth of field, making the corn in sharp focus and the background slightly blurred.",
    "High-resolution DSLR photo of a single whole with white background, unsliced beetroot with deep red-purple skin. The beetroot is flying in space 1000 meters, with no plain underneath is shown. neutral background with soft, natural lighting and a shallow depth of field, making the beetroot in sharp focus and the background slightly blurred."
]
'''

prompts = [
    "High-resolution DSLR photo of a large ceramic bowl with a glossy white finish, placed on a white surface with a neutral soft shadow underneath. The bowl is shown from a slight top angle with soft lighting that highlights its smooth surface.",
    "High-resolution DSLR photo of a rustic wooden bowl, showcasing its deep curvature and natural grain patterns. The bowl is placed on a wooden table with a warm ambient light source, highlighting the textures of both the bowl and the surface.",
    "High-resolution DSLR photo of a polished bronze bowl with intricate engravings along its rim. The bowl is placed in a dimly lit room with a spotlight on its metallic surface, giving it a rich, reflective sheen.",
    "High-resolution DSLR photo of a transparent glass bowl with a subtle blue tint, floating mid-air in a minimalist white background. The light reflections on the glass are sharp, giving it a crisp and delicate appearance.",
    "High-resolution DSLR photo of a stone bowl with a weathered texture and irregular edges, resting on a bed of gravel in an outdoor setting. The lighting emphasizes the natural roughness of the stone.",
    "High-resolution DSLR photo of a sleek, modern matte black ceramic bowl, placed on a dark reflective surface. The contrast between the bowl and the surface highlights the minimalist, elegant design.",
    "High-resolution DSLR photo of a hand-painted porcelain bowl with colorful floral designs, placed on a rustic wooden table. The lighting enhances the glossy finish, making the colors of the floral designs pop.",
    "High-resolution DSLR photo of a hammered copper bowl with an antique patina, floating in mid-air with a soft spotlight on it. The texture of the metal is clearly visible, with subtle greenish oxidation on the surface.",
    "High-resolution DSLR photo of a shallow bamboo bowl, placed on a white countertop. The woven texture is in sharp focus, with soft lighting emphasizing the natural tan color of the bamboo.",
    "High-resolution DSLR photo of a bright red glossy plastic bowl, placed on a reflective surface. The lighting creates vibrant reflections, emphasizing the bowl's smooth and shiny surface.",
    "High-resolution DSLR photo of a marble bowl with elegant grey veins running through it. The bowl is placed on a marble countertop, with soft lighting that highlights the bowl's polished surface.",
    "High-resolution DSLR photo of a woven rattan bowl, sitting on a beige linen cloth. The lighting is warm, emphasizing the natural texture and slight flexibility of the woven fibers.",
    "High-resolution DSLR photo of a dark cast iron bowl with a rough surface, sitting on a rustic wooden table. The lighting is moody, with shadows that enhance the texture and heavy appearance of the bowl.",
    "High-resolution DSLR photo of a ceramic bowl with a crackle glaze effect. The bowl is placed on a smooth white surface, with lighting that highlights the intricate crack patterns in the glaze.",
    "High-resolution DSLR photo of a paper mâché bowl, placed on a rustic wooden table. The hand-painted abstract designs are vibrant and the texture of the paper is clearly visible in the soft lighting.",
    "High-resolution DSLR photo of a stoneware bowl with a matte charcoal finish, placed on a concrete surface. The lighting is diffuse, emphasizing the tactile surface of the bowl and its modern aesthetic.",
    "High-resolution DSLR photo of a crystal-cut glass bowl, placed on a white reflective surface with sharp geometric patterns that catch and reflect light in a prismatic way.",
    "High-resolution DSLR photo of a gold-leaf bowl with an ornate rim, sitting on a black velvet cloth. The soft lighting highlights the reflective, luxurious surface of the thin metal.",
    "High-resolution DSLR photo of a rough concrete bowl, placed on an industrial-style metal surface. The lighting is stark, bringing out the bowl's rough texture and light grey tone.",
    "High-resolution DSLR photo of a resin bowl with a smooth translucent body, placed on a black background. Inside the resin are colorful fragments that glow softly under diffused lighting.",
    "High-resolution DSLR photo of a cork bowl, resting on a wooden surface. The texture of the cork is soft and porous, and the lighting is warm, making the bowl appear lightweight and natural.",
    "High-resolution DSLR photo of a bright orange silicone bowl, placed on a reflective surface. The bowl's flexible texture is in sharp focus, with smooth curves and a matte finish.",
    "High-resolution DSLR photo of a lacquered wooden bowl, deep black with glossy red hand-painted accents, placed on a black surface. The bowl shines under a soft spotlight, showing off its polished surface.",
    "High-resolution DSLR photo of a clay bowl with hand-shaped imperfections and a warm terracotta color, sitting on a rustic stone surface. The soft lighting emphasizes the earthy texture of the bowl.",
    "High-resolution DSLR photo of a stainless steel bowl, floating in mid-air against a black background. The bowl's mirror-like reflective surface captures soft, diffused light, giving it a sleek, modern look.",
    "High-resolution DSLR photo of a porcelain bowl with a minimalist pure white design, sitting on a white marble surface. The lighting is soft and even, highlighting the bowl's seamless, smooth curves.",
    "High-resolution DSLR photo of a plaster bowl with a rough chalky surface, placed on a stone surface. The white bowl has slight cracks and irregular edges, giving it a rustic appearance.",
    "High-resolution DSLR photo of a dark green fiberglass bowl, placed on a wooden surface. The bowl's glossy finish catches soft light, making its lightweight, deep form clearly visible.",
    "High-resolution DSLR photo of a hand-sculpted clay bowl with ridges along its sides, placed on a natural stone background. The warm natural lighting highlights the bowl’s handmade aesthetic and brown tones.",
    "High-resolution DSLR photo of an alabaster bowl with soft translucency, placed on a white surface. The lighting subtly passes through the bowl, highlighting its off-white, smooth texture.",
    "High-resolution DSLR photo of a beaded wireframe bowl made from silver wire, resting on a glass surface. The intricate patterns of the bowl's wire construction cast delicate shadows in soft lighting.",
    "High-resolution DSLR photo of a ceramic bowl with a gradient glaze, placed on a white countertop. The bowl's glaze fades from dark blue at the base to light aqua near the rim, with a smooth finish.",
    "High-resolution DSLR photo of a jute bowl with a fibrous texture, sitting on a linen surface. The soft, natural lighting emphasizes the slight irregularities in the bowl's woven structure.",
    "High-resolution DSLR photo of a sandstone bowl, placed on a stone surface. The warm, textured surface of the bowl is highlighted by the ambient outdoor light, showcasing subtle carvings.",
    "High-resolution DSLR photo of a tarnished pewter bowl with dents and uneven edges, placed on a dark wooden table. The lighting casts soft shadows that emphasize the bowl's antique appearance.",
    "High-resolution DSLR photo of a matte black polymer bowl with sharp angular lines, placed on a futuristic metallic surface. The bowl's geometric shape is in sharp focus under bright, artificial lighting.",
    "High-resolution DSLR photo of a smooth black soapstone bowl with subtle grey marbling, placed on a white marble surface. The soft lighting highlights the cool, smooth texture of the stone.",
    "High-resolution DSLR photo of a neon green plastic bowl, placed on a reflective surface. The bowl's glossy finish is sharp under the bright lighting, giving it a vibrant, modern appearance.",
    "High-resolution DSLR photo of a hand-carved mahogany bowl with intricate designs, placed on a velvet cloth. The deep red-brown wood shines softly in the warm lighting, bringing out the polished surface.",
    "High-resolution DSLR photo of a white 3D-printed bowl with a complex lattice pattern, placed on a reflective black surface. The bowl's geometric shape is in sharp focus, with shadows from the intricate design.",
    "High-resolution DSLR photo of a pearlescent seashell bowl, floating mid-air with a white background. The soft lighting brings out the natural spiral texture and iridescent sheen.",
    "High-resolution DSLR photo of a hand-painted terra cotta bowl with bold tribal patterns, placed on a rustic wooden table. The bowl's rough, porous texture is accentuated by the warm natural lighting.",
    "High-resolution DSLR photo of a porcelain bowl with gold trim around its edges, placed on a white marble surface. The lighting highlights the glossy surface and delicate floral print inside.",
    "High-resolution DSLR photo of a flexible turquoise silicone bowl, placed on a white reflective surface. The smooth, soft material catches diffused light, showing its lightweight, rounded shape.",
    "High-resolution DSLR photo of a carved pale green soapstone bowl, resting on a linen cloth. The intricate floral etchings along the sides are in sharp focus under soft, natural lighting.",
    "High-resolution DSLR photo of a brushed aluminum bowl, floating mid-air with a neutral background. The sleek metallic surface is sharply defined by bright, direct lighting.",
    "High-resolution DSLR photo of a purple velvet-covered bowl, placed on a black surface. The soft fabric texture and deep color are highlighted by subtle lighting, giving the bowl an elegant appearance.",
    "High-resolution DSLR photo of a speckled ceramic bowl with a textured beige and grey glaze, placed on a wooden surface. The soft lighting enhances the bowl's slightly uneven, artisanal look.",
    "High-resolution DSLR photo of a carved ivory-tone bone bowl, resting on a dark stone surface. The lighting is low, casting shadows that emphasize the intricate organic patterns.",
    "High-resolution DSLR photo of a futuristic carbon fiber bowl, placed on a metal table. The matte black finish and sleek, lightweight design are highlighted by bright, artificial light."
]





negative_prompt = "shadow, shiny, water, damaged, broken, unrealistic, light reflexion, drops, sliced, cut, peeled, half, piece, ugly, tiling, out of frame, poorly drawn face, extra limbs, disfigured, deformed, body out of frame, blurry, bad anatomy, blurred, artifacts, bad proportions."


for prompt_index, prompt in enumerate(prompts):
    for image_index in range(5):
        seed = random.randint(0, 2147483647)  
        generator = torch.manual_seed(seed)
        image = pipe(prompt,negative_prompt=negative_prompt,num_inference_steps=28,guidance_scale=5,generator=generator).images[0]
        image.save(f"/lustre/fsn1/projects/rech/tya/ubn15wo/3D_GEN/bol_images/bol_prompt{prompt_index}_{image_index + 1}.jpg")

        #image.save(f"/lustre/fsn1/projects/rech/tya/ubn15wo/3D_GEN/fruit_images/{get_fruit_name(prompts[prompt_index])}_{image_index + 1}.jpg")
        #print("generated : ", f"/lustre/fsn1/projects/rech/tya/ubn15wo/3D_GEN/fruit_images/{get_fruit_name(prompts[prompt_index])}_{image_index + 1}.jpg")

